// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFakTwDW502Xu7FPrbmAvQoZ27fD2-4II',
    appId: '1:344065683187:web:de9bfc8a708850503d5186',
    messagingSenderId: '344065683187',
    projectId: 'liberapp-10a5c',
    authDomain: 'liberapp-10a5c.firebaseapp.com',
    storageBucket: 'liberapp-10a5c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa51C3qqEsVasK9NQyj31dqcVnoqSMcFI',
    appId: '1:344065683187:android:5b59b5343279fc6b3d5186',
    messagingSenderId: '344065683187',
    projectId: 'liberapp-10a5c',
    storageBucket: 'liberapp-10a5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWK3r_UCcKpEA2FJ0dfWo6YE2W9lBDU20',
    appId: '1:344065683187:ios:b2d7e8f5aa2ecc4a3d5186',
    messagingSenderId: '344065683187',
    projectId: 'liberapp-10a5c',
    storageBucket: 'liberapp-10a5c.appspot.com',
    iosClientId: '344065683187-dk53e5g422kshr5uvjmpobc2d7i1tn24.apps.googleusercontent.com',
    iosBundleId: 'com.example.liberapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWK3r_UCcKpEA2FJ0dfWo6YE2W9lBDU20',
    appId: '1:344065683187:ios:b2d7e8f5aa2ecc4a3d5186',
    messagingSenderId: '344065683187',
    projectId: 'liberapp-10a5c',
    storageBucket: 'liberapp-10a5c.appspot.com',
    iosClientId: '344065683187-dk53e5g422kshr5uvjmpobc2d7i1tn24.apps.googleusercontent.com',
    iosBundleId: 'com.example.liberapp',
  );
}
